# Generated by Django 2.1.3 on 2018-11-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.PositiveIntegerField()),
                ('char', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='links',
        ),
        migrations.RemoveField(
            model_name='gituser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='gituser',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gituser',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
