# Generated by Django 2.1.3 on 2018-11-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('githubApp', '0002_auto_20181126_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='char',
            new_name='destination',
        ),
    ]
