# Generated by Django 2.1.3 on 2018-11-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubApp', '0003_auto_20181126_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gituser',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
