# Generated by Django 2.1.3 on 2018-11-26 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('githubApp', '0004_auto_20181126_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='destination',
            new_name='target',
        ),
    ]
