# Generated by Django 2.1.3 on 2018-11-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubApp', '0005_auto_20181126_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='target',
            field=models.CharField(max_length=100),
        ),
    ]
