# Generated by Django 2.1.3 on 2018-11-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubApp', '0006_auto_20181126_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gituser',
            name='weight',
        ),
        migrations.AddField(
            model_name='link',
            name='weight',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
